# Run tests.
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn test
      - run: yarn workspace e2e-tests-gatsby-theme-core test:e2e:ci
      - run: yarn workspace e2e-tests-gatsby-theme-block test:e2e:ci
      # - run: yarn workspace e2e-tests-blocks test:e2e:ci
      # - run: yarn workspace www test:e2e:ci
      #   env:
      #     ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      #     ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      #     ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
      #     ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
